"""Forge tools. Generates training scripts from mission briefs."""

import logging
import os

from agents.forge.decision_tree import select_architecture

logger = logging.getLogger(__name__)


def read_mission_brief(brief_data: dict) -> dict:
    return brief_data


def define_optuna_space(architecture: str) -> dict:
    spaces = {
        "lightgbm": {
            "num_leaves": {"type": "int", "low": 16, "high": 256},
            "learning_rate": {"type": "float", "low": 0.01, "high": 0.3},
            "subsample": {"type": "float", "low": 0.6, "high": 1.0},
            "colsample_bytree": {"type": "float", "low": 0.6, "high": 1.0},
            "min_child_samples": {"type": "int", "low": 5, "high": 100},
            "reg_alpha": {"type": "float", "low": 0.0, "high": 10.0},
            "reg_lambda": {"type": "float", "low": 0.0, "high": 10.0},
        },
        "xgboost": {
            "max_depth": {"type": "int", "low": 3, "high": 12},
            "learning_rate": {"type": "float", "low": 0.01, "high": 0.3},
            "subsample": {"type": "float", "low": 0.6, "high": 1.0},
            "colsample_bytree": {"type": "float", "low": 0.6, "high": 1.0},
            "min_child_weight": {"type": "float", "low": 1, "high": 10},
            "reg_alpha": {"type": "float", "low": 0.0, "high": 10.0},
        },
        "tabnet": {
            "n_d": {"type": "int", "low": 8, "high": 64},
            "n_a": {"type": "int", "low": 8, "high": 64},
            "n_steps": {"type": "int", "low": 3, "high": 10},
            "gamma": {"type": "float", "low": 1.0, "high": 2.0},
            "lambda_sparse": {"type": "float", "low": 0.0, "high": 0.01},
            "learning_rate": {"type": "float", "low": 0.001, "high": 0.05},
            "batch_size": {"type": "int", "low": 64, "high": 512},
        },
        "distilbert": {
            "learning_rate": {"type": "float", "low": 5e-6, "high": 5e-4},
            "num_train_epochs": {"type": "int", "low": 2, "high": 8},
            "per_device_batch_size": {"type": "int", "low": 8, "high": 32},
            "weight_decay": {"type": "float", "low": 0.0, "high": 0.1},
            "warmup_ratio": {"type": "float", "low": 0.0, "high": 0.3},
        },
        "efficientnet": {
            "learning_rate": {"type": "float", "low": 1e-5, "high": 1e-2},
            "num_epochs": {"type": "int", "low": 10, "high": 100},
            "batch_size": {"type": "int", "low": 16, "high": 128},
            "weight_decay": {"type": "float", "low": 0.0, "high": 0.1},
            "label_smoothing": {"type": "float", "low": 0.0, "high": 0.2},
        },
    }
    return spaces.get(architecture, {})


def write_training_script(mission_brief: dict, job_id: str, scripts_dir: str = "./scripts") -> str:
    architecture = select_architecture(mission_brief)
    task_type = mission_brief["task_type"]
    target = mission_brief.get("target_column", "target")
    file_path = mission_brief["dataset"]["file_path"]
    is_classification = task_type == "classification"

    data_filename = os.path.basename(file_path)

    target_line = f'target = df.pop("{target}")' if target else "target = df.iloc[:, -1]"
    eval_metrics = (
        'from sklearn.metrics import roc_auc_score, f1_score, accuracy_score\nprint(f"Accuracy: {accuracy_score(y_test, y_pred):.4f}")'
        if is_classification
        else 'from sklearn.metrics import mean_squared_error\nrmse = float(np.sqrt(mean_squared_error(y_test, y_pred)))\nprint(f"RMSE: {rmse:.4f}")'
    )

    # Use DATA_DIR / OUTPUTS_DIR env vars so the script works both on the host
    # (defaults: ./data, ./outputs) and inside a Docker container (/app/data, /app/outputs).
    # Optuna hyperparameter search kicks in when SEARCH_SPACE_JSON env var is set.
    direction = '"maximize"' if is_classification else '"minimize"'

    script = f'''"""
Training script for job {job_id}
Architecture: {architecture}
Task: {task_type}
Auto-generated by Forge agent.
"""

import os
import json
import pickle
import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, OrdinalEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
import lightgbm as lgb

# --- Optional Optuna hyperparameter search ---
_search_space_json = os.getenv("SEARCH_SPACE_JSON")
_use_optuna = bool(_search_space_json)
if _use_optuna:
    import optuna
    _search_space = json.loads(_search_space_json)

# --- Data loading (DATA_DIR env var for container-relative paths) ---
_data_dir = os.getenv("DATA_DIR", "./data")
df = pd.read_csv(os.path.join(_data_dir, "{data_filename}"))
{target_line}

# Drop high-cardinality text columns (Name, Ticket, Cabin)
for col in ["Name", "Ticket", "Cabin"]:
    if col in df.columns:
        df.drop(columns=[col], inplace=True)

X_train, X_test, y_train, y_test = train_test_split(
    df, target, test_size=0.2, random_state=42
)

# --- Preprocessing ---
numeric_cols = X_train.select_dtypes(include=["int64", "float64"]).columns.tolist()
categorical_cols = X_train.select_dtypes(include=["object"]).columns.tolist()

preprocessor = ColumnTransformer([
    ("num", "passthrough", numeric_cols),
    ("cat", OrdinalEncoder(handle_unknown="use_encoded_value", unknown_value=-1), categorical_cols),
])

# --- Hyperparameter search (Optuna) or defaults ---
if _use_optuna:
    if {is_classification}:
        def _objective(trial):
            params = {{}}
            for _name, _spec in _search_space.items():
                if _spec["type"] == "int":
                    params[_name] = trial.suggest_int(_name, _spec["low"], _spec["high"])
                elif _spec["type"] == "float":
                    params[_name] = trial.suggest_float(_name, _spec["low"], _spec["high"])
            params["random_state"] = 42
            params["verbose"] = -1
            _model = Pipeline([("preprocessor", preprocessor), ("estimator", lgb.LGBMClassifier(**params))])
            _model.fit(X_train, y_train)
            _y_pred = _model.predict(X_test)
            from sklearn.metrics import accuracy_score
            return accuracy_score(y_test, _y_pred)
    else:
        def _objective(trial):
            params = {{}}
            for _name, _spec in _search_space.items():
                if _spec["type"] == "int":
                    params[_name] = trial.suggest_int(_name, _spec["low"], _spec["high"])
                elif _spec["type"] == "float":
                    params[_name] = trial.suggest_float(_name, _spec["low"], _spec["high"])
            params["random_state"] = 42
            params["verbose"] = -1
            _model = Pipeline([("preprocessor", preprocessor), ("estimator", lgb.LGBMRegressor(**params))])
            _model.fit(X_train, y_train)
            _y_pred = _model.predict(X_test)
            from sklearn.metrics import mean_squared_error
            return float(mean_squared_error(y_test, _y_pred))

    _n_trials = int(os.getenv("OPTUNA_TRIALS", "10"))
    study = optuna.create_study(direction={direction})
    study.optimize(_objective, n_trials=_n_trials)
    best_params = study.best_params
    best_params["random_state"] = 42
    best_params["verbose"] = -1
else:
    best_params = {{"n_estimators": 100, "random_state": 42, "verbose": -1}}

if {is_classification}:
    estimator = lgb.LGBMClassifier(**best_params)
else:
    estimator = lgb.LGBMRegressor(**best_params)

model = Pipeline([
    ("preprocessor", preprocessor),
    ("estimator", estimator),
])
model.fit(X_train, y_train)

# --- Evaluation ---
y_pred = model.predict(X_test)
{eval_metrics}

# --- Save checkpoint (OUTPUTS_DIR env var for container-relative paths) ---
_outputs_dir = os.getenv("OUTPUTS_DIR", "./outputs")
output_dir = os.path.join(_outputs_dir, "{job_id}", "checkpoints")
os.makedirs(output_dir, exist_ok=True)
checkpoint_path = os.path.join(output_dir, "best.ckpt")
with open(checkpoint_path, "wb") as f:
    pickle.dump(model, f)
print(f"Model saved to {{checkpoint_path}}")
'''

    script_path = os.path.join(scripts_dir, f"training_script_{job_id}.py")
    os.makedirs(scripts_dir, exist_ok=True)
    with open(script_path, "w") as f:
        f.write(script)

    logger.info(f"[job={job_id}] Training script written to {script_path}")
    return script_path
