"""Forge tools. Generates training scripts from mission briefs."""

import logging
import os

from agents.forge.decision_tree import select_architecture

logger = logging.getLogger(__name__)


def read_mission_brief(brief_data: dict) -> dict:
    return brief_data


def define_optuna_space(architecture: str) -> dict:
    spaces = {
        "lightgbm": {
            "num_leaves": {"type": "int", "low": 16, "high": 256},
            "learning_rate": {"type": "float", "low": 0.01, "high": 0.3},
            "subsample": {"type": "float", "low": 0.6, "high": 1.0},
            "colsample_bytree": {"type": "float", "low": 0.6, "high": 1.0},
            "min_child_samples": {"type": "int", "low": 5, "high": 100},
            "reg_alpha": {"type": "float", "low": 0.0, "high": 10.0},
            "reg_lambda": {"type": "float", "low": 0.0, "high": 10.0},
        },
        "xgboost": {
            "max_depth": {"type": "int", "low": 3, "high": 12},
            "learning_rate": {"type": "float", "low": 0.01, "high": 0.3},
            "subsample": {"type": "float", "low": 0.6, "high": 1.0},
            "colsample_bytree": {"type": "float", "low": 0.6, "high": 1.0},
            "min_child_weight": {"type": "float", "low": 1, "high": 10},
            "reg_alpha": {"type": "float", "low": 0.0, "high": 10.0},
        },
        "tabnet": {
            "n_d": {"type": "int", "low": 8, "high": 64},
            "n_a": {"type": "int", "low": 8, "high": 64},
            "n_steps": {"type": "int", "low": 3, "high": 10},
            "gamma": {"type": "float", "low": 1.0, "high": 2.0},
            "lambda_sparse": {"type": "float", "low": 0.0, "high": 0.01},
            "learning_rate": {"type": "float", "low": 0.001, "high": 0.05},
            "batch_size": {"type": "int", "low": 64, "high": 512},
        },
        "distilbert": {
            "learning_rate": {"type": "float", "low": 5e-6, "high": 5e-4},
            "num_train_epochs": {"type": "int", "low": 2, "high": 8},
            "per_device_batch_size": {"type": "int", "low": 8, "high": 32},
            "weight_decay": {"type": "float", "low": 0.0, "high": 0.1},
            "warmup_ratio": {"type": "float", "low": 0.0, "high": 0.3},
        },
        "efficientnet": {
            "learning_rate": {"type": "float", "low": 1e-5, "high": 1e-2},
            "num_epochs": {"type": "int", "low": 10, "high": 100},
            "batch_size": {"type": "int", "low": 16, "high": 128},
            "weight_decay": {"type": "float", "low": 0.0, "high": 0.1},
            "label_smoothing": {"type": "float", "low": 0.0, "high": 0.2},
        },
    }
    return spaces.get(architecture, {})


def write_training_script(mission_brief: dict, job_id: str, scripts_dir: str = "./scripts") -> str:
    architecture = select_architecture(mission_brief)

    # Dispatch to modality-specific script generators
    if architecture == "distilbert":
        return _write_distilbert_script(mission_brief, job_id, scripts_dir)
    elif architecture == "efficientnet":
        return _write_efficientnet_script(mission_brief, job_id, scripts_dir)

    return _write_lightgbm_script(mission_brief, job_id, scripts_dir)


def _write_lightgbm_script(mission_brief: dict, job_id: str, scripts_dir: str = "./scripts") -> str:
    task_type = mission_brief["task_type"]
    target = mission_brief.get("target_column", "target")
    file_path = mission_brief["dataset"]["file_path"]
    is_classification = task_type == "classification"
    data_filename = os.path.basename(file_path)

    target_line = f'target = df.pop("{target}")' if target else "target = df.iloc[:, -1]"
    eval_metrics = (
        'from sklearn.metrics import roc_auc_score, f1_score, accuracy_score\nprint(f"Accuracy: {accuracy_score(y_test, y_pred):.4f}")'
        if is_classification
        else 'from sklearn.metrics import mean_squared_error\nrmse = float(np.sqrt(mean_squared_error(y_test, y_pred)))\nprint(f"RMSE: {rmse:.4f}")'
    )
    direction = '"maximize"' if is_classification else '"minimize"'

    script = f'''"""
Training script for job {job_id}
Architecture: lightgbm
Task: {task_type}
Auto-generated by Forge agent.
"""

import os
import json
import pickle
import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, OrdinalEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
import lightgbm as lgb

_search_space_json = os.getenv("SEARCH_SPACE_JSON")
_use_optuna = bool(_search_space_json)
if _use_optuna:
    import optuna
    _search_space = json.loads(_search_space_json)

_data_dir = os.getenv("DATA_DIR", "./data")
df = pd.read_csv(os.path.join(_data_dir, "{data_filename}"))
{target_line}

for col in ["Name", "Ticket", "Cabin"]:
    if col in df.columns:
        df.drop(columns=[col], inplace=True)

X_train, X_test, y_train, y_test = train_test_split(
    df, target, test_size=0.2, random_state=42
)

numeric_cols = X_train.select_dtypes(include=["int64", "float64"]).columns.tolist()
categorical_cols = X_train.select_dtypes(include=["object"]).columns.tolist()

preprocessor = ColumnTransformer([
    ("num", "passthrough", numeric_cols),
    ("cat", OrdinalEncoder(handle_unknown="use_encoded_value", unknown_value=-1), categorical_cols),
])

if _use_optuna:
    if {is_classification}:
        def _objective(trial):
            params = {{}}
            for _name, _spec in _search_space.items():
                if _spec["type"] == "int":
                    params[_name] = trial.suggest_int(_name, _spec["low"], _spec["high"])
                elif _spec["type"] == "float":
                    params[_name] = trial.suggest_float(_name, _spec["low"], _spec["high"])
            params["random_state"] = 42
            params["verbose"] = -1
            _model = Pipeline([("preprocessor", preprocessor), ("estimator", lgb.LGBMClassifier(**params))])
            _model.fit(X_train, y_train)
            _y_pred = _model.predict(X_test)
            from sklearn.metrics import accuracy_score
            return accuracy_score(y_test, _y_pred)
    else:
        def _objective(trial):
            params = {{}}
            for _name, _spec in _search_space.items():
                if _spec["type"] == "int":
                    params[_name] = trial.suggest_int(_name, _spec["low"], _spec["high"])
                elif _spec["type"] == "float":
                    params[_name] = trial.suggest_float(_name, _spec["low"], _spec["high"])
            params["random_state"] = 42
            params["verbose"] = -1
            _model = Pipeline([("preprocessor", preprocessor), ("estimator", lgb.LGBMRegressor(**params))])
            _model.fit(X_train, y_train)
            _y_pred = _model.predict(X_test)
            from sklearn.metrics import mean_squared_error
            return float(mean_squared_error(y_test, _y_pred))

    _n_trials = int(os.getenv("OPTUNA_TRIALS", "10"))
    study = optuna.create_study(direction={direction})
    study.optimize(_objective, n_trials=_n_trials)
    best_params = study.best_params
    best_params["random_state"] = 42
    best_params["verbose"] = -1
else:
    best_params = {{"n_estimators": 100, "random_state": 42, "verbose": -1}}

if {is_classification}:
    estimator = lgb.LGBMClassifier(**best_params)
else:
    estimator = lgb.LGBMRegressor(**best_params)

model = Pipeline([
    ("preprocessor", preprocessor),
    ("estimator", estimator),
])
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
{eval_metrics}

_outputs_dir = os.getenv("OUTPUTS_DIR", "./outputs")
output_dir = os.path.join(_outputs_dir, "{job_id}", "checkpoints")
os.makedirs(output_dir, exist_ok=True)
checkpoint_path = os.path.join(output_dir, "best.ckpt")
with open(checkpoint_path, "wb") as f:
    pickle.dump(model, f)
print(f"Model saved to {{checkpoint_path}}")
np.save(os.path.join(output_dir, "y_test.npy"), y_test)
np.save(os.path.join(output_dir, "y_pred.npy"), y_pred)
if {is_classification}:
    y_prob_full = model.predict_proba(X_test)
    if y_prob_full.shape[1] == 2:
        y_prob_full = y_prob_full[:, 1]
    np.save(os.path.join(output_dir, "y_prob.npy"), y_prob_full)
'''

    script_path = os.path.join(scripts_dir, f"training_script_{job_id}.py")
    os.makedirs(scripts_dir, exist_ok=True)
    with open(script_path, "w", encoding="utf-8") as f:
        f.write(script)

    logger.info(f"[job={job_id}] LightGBM script written to {script_path}")
    return script_path


def _write_distilbert_script(
    mission_brief: dict, job_id: str, scripts_dir: str = "./scripts"
) -> str:
    task_type = mission_brief["task_type"]
    target = mission_brief.get("target_column", "target")
    file_path = mission_brief["dataset"]["file_path"]
    data_filename = os.path.basename(file_path)

    script = f'''"""
Training script for job {job_id}
Architecture: distilbert
Task: {task_type}
Auto-generated by Forge agent.
"""

import os
import json
import pickle
import warnings
import numpy as np
import pandas as pd
import torch
from torch.utils.data import DataLoader, Dataset
from transformers import DistilBertTokenizer, DistilBertForSequenceClassification, AdamW
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder
warnings.filterwarnings("ignore")

JOB_ID = "{job_id}"
DATA_PATH = os.path.join(os.getenv("DATA_DIR", "./data"), "{data_filename}")
TARGET_COL = "{target}"
OUTPUT_DIR = os.path.join(os.getenv("OUTPUTS_DIR", "./outputs"), JOB_ID, "checkpoints")
os.makedirs(OUTPUT_DIR, exist_ok=True)

df = pd.read_csv(DATA_PATH)
text_col = [c for c in df.columns if c != TARGET_COL and df[c].dtype == "object"][0]
texts = df[text_col].astype(str).tolist()
labels = df[TARGET_COL].values

le = LabelEncoder()
labels = le.fit_transform(labels)
num_labels = len(le.classes_)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
tokenizer = DistilBertTokenizer.from_pretrained("distilbert-base-uncased")
model = DistilBertForSequenceClassification.from_pretrained("distilbert-base-uncased", num_labels=num_labels)
model.to(device)

class TextDataset(Dataset):
    def __init__(self, texts, labels):
        self.encodings = tokenizer(texts, truncation=True, padding=True, max_length=128, return_tensors="pt")
        self.labels = torch.tensor(labels)
    def __len__(self): return len(self.labels)
    def __getitem__(self, idx):
        item = {{k: v[idx] for k, v in self.encodings.items()}}
        item["labels"] = self.labels[idx]
        return item

train_texts, val_texts, train_labels, val_labels = train_test_split(texts, labels, test_size=0.2, random_state=42)
train_dataset = TextDataset(train_texts, train_labels)
val_dataset = TextDataset(val_texts, val_labels)
train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=16)

optimizer = AdamW(model.parameters(), lr=2e-5)

for epoch in range(3):
    model.train()
    total_loss = 0
    for batch in train_loader:
        batch = {{k: v.to(device) for k, v in batch.items()}}
        outputs = model(**batch)
        loss = outputs.loss
        loss.backward()
        optimizer.step()
        optimizer.zero_grad()
        total_loss += loss.item()
    avg_loss = total_loss / len(train_loader)
    print(f"Epoch {{epoch+1}}/3 | Train loss: {{avg_loss:.4f}}")

    model.eval()
    all_preds, all_labels = [], []
    with torch.no_grad():
        for batch in val_loader:
            batch = {{k: v.to(device) for k, v in batch.items()}}
            outputs = model(**batch)
            preds = torch.argmax(outputs.logits, dim=-1)
            all_preds.extend(preds.cpu().numpy())
            all_labels.extend(batch["labels"].cpu().numpy())
    val_acc = accuracy_score(all_labels, all_preds)
    print(f"Accuracy: {{val_acc:.4f}}")

checkpoint_path = os.path.join(OUTPUT_DIR, "best.ckpt")
with open(checkpoint_path, "wb") as f:
    pickle.dump({{"model_state": model.state_dict(), "label_encoder": le}}, f)
print(f"Model saved to {{checkpoint_path}}")
np.save(os.path.join(OUTPUT_DIR, "y_test.npy"), np.array(val_labels))
np.save(os.path.join(OUTPUT_DIR, "y_pred.npy"), np.array(all_preds))

result = {{"checkpoint_path": checkpoint_path, "val_score": float(val_acc), "metric": "accuracy"}}
with open(os.path.join("outputs", JOB_ID, "result.json"), "w") as f:
    json.dump(result, f)
print("TRAINING_COMPLETE")
'''

    script_path = os.path.join(scripts_dir, f"training_script_{job_id}.py")
    os.makedirs(scripts_dir, exist_ok=True)
    with open(script_path, "w", encoding="utf-8") as f:
        f.write(script)

    logger.info(f"[job={job_id}] DistilBERT script written to {script_path}")
    return script_path


def _write_efficientnet_script(
    mission_brief: dict, job_id: str, scripts_dir: str = "./scripts"
) -> str:
    task_type = mission_brief["task_type"]
    file_path = mission_brief["dataset"]["file_path"]
    data_filename = os.path.basename(file_path)

    script = f'''"""
Training script for job {job_id}
Architecture: efficientnet
Task: {task_type}
Auto-generated by Forge agent.
"""

import os
import json
import pickle
import warnings
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, Dataset
from torchvision import transforms, models
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder
from PIL import Image
warnings.filterwarnings("ignore")

JOB_ID = "{job_id}"
DATA_PATH = os.path.join(os.getenv("DATA_DIR", "./data"), "{data_filename}")
OUTPUT_DIR = os.path.join(os.getenv("OUTPUTS_DIR", "./outputs"), JOB_ID, "checkpoints")
os.makedirs(OUTPUT_DIR, exist_ok=True)

df = pd.read_csv(DATA_PATH)
img_col = [c for c in df.columns if "path" in c.lower() or "file" in c.lower() or "image" in c.lower()]
label_col = [c for c in df.columns if c != img_col[0]][0] if img_col else df.columns[-1]
img_col = img_col[0] if img_col else df.columns[0]

le = LabelEncoder()
labels = le.fit_transform(df[label_col])
num_classes = len(le.classes_)

transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
])

class ImageDataset(Dataset):
    def __init__(self, paths, labels, transform):
        self.paths = paths.tolist()
        self.labels = torch.tensor(labels)
        self.transform = transform
    def __len__(self): return len(self.paths)
    def __getitem__(self, idx):
        img = Image.open(self.paths[idx]).convert("RGB")
        img = self.transform(img)
        return {{"pixel_values": img, "labels": self.labels[idx]}}

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = models.efficientnet_b0(pretrained=True)
model.classifier[1] = nn.Linear(model.classifier[1].in_features, num_classes)
model.to(device)

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

train_idx, val_idx = train_test_split(range(len(df)), test_size=0.2, random_state=42)
train_ds = ImageDataset(df[img_col].values[train_idx], labels[train_idx], transform)
val_ds = ImageDataset(df[img_col].values[val_idx], labels[val_idx], transform)
train_loader = DataLoader(train_ds, batch_size=32, shuffle=True)
val_loader = DataLoader(val_ds, batch_size=32)

for epoch in range(10):
    model.train()
    total_loss = 0
    for batch in train_loader:
        batch = {{k: v.to(device) for k, v in batch.items()}}
        outputs = model(**batch)
        logits = outputs.logits if hasattr(outputs, 'logits') else outputs
        loss = criterion(logits, batch["labels"])
        loss.backward()
        optimizer.step()
        optimizer.zero_grad()
        total_loss += loss.item()
    avg_loss = total_loss / len(train_loader)
    print(f"Epoch {{epoch+1}}/10 | Train loss: {{avg_loss:.4f}}")

    model.eval()
    all_preds, all_labels = [], []
    with torch.no_grad():
        for batch in val_loader:
            batch = {{k: v.to(device) for k, v in batch.items()}}
            outputs = model(**batch)
            logits = outputs.logits if hasattr(outputs, 'logits') else outputs
            preds = torch.argmax(logits, dim=-1)
            all_preds.extend(preds.cpu().numpy())
            all_labels.extend(batch["labels"].cpu().numpy())
    val_acc = accuracy_score(all_labels, all_preds)
    print(f"Accuracy: {{val_acc:.4f}}")

checkpoint_path = os.path.join(OUTPUT_DIR, "best.ckpt")
torch.save({{"model_state": model.state_dict(), "label_encoder": le}}, checkpoint_path)
print(f"Model saved to {{checkpoint_path}}")
np.save(os.path.join(OUTPUT_DIR, "y_test.npy"), np.array(all_labels))
np.save(os.path.join(OUTPUT_DIR, "y_pred.npy"), np.array(all_preds))

result = {{"checkpoint_path": checkpoint_path, "val_score": float(val_acc), "metric": "accuracy"}}
with open(os.path.join("outputs", JOB_ID, "result.json"), "w") as f:
    json.dump(result, f)
print("TRAINING_COMPLETE")
'''

    script_path = os.path.join(scripts_dir, f"training_script_{job_id}.py")
    os.makedirs(scripts_dir, exist_ok=True)
    with open(script_path, "w", encoding="utf-8") as f:
        f.write(script)

    logger.info(f"[job={job_id}] EfficientNet script written to {script_path}")
    return script_path
