"""
Training script for job test-job-metric
Architecture: lightgbm
Task: binary_classification
Auto-generated by Forge template engine.
"""

import os
import json
import pickle
import warnings

import numpy as np
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.metrics import accuracy_score, roc_auc_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OrdinalEncoder
from sklearn.pipeline import Pipeline
import lightgbm as lgb

warnings.filterwarnings("ignore")

_search_space_json = os.getenv("SEARCH_SPACE_JSON")
_use_optuna = bool(_search_space_json)
if _use_optuna:
    import optuna
    _search_space = json.loads(_search_space_json)

_data_dir = os.getenv("DATA_DIR", "./data")
df = pd.read_csv(os.path.join(_data_dir, "data.csv"))
target = df.pop("target")

mask = target.notna()
df = df[mask]
target = target[mask]

for _c in df.select_dtypes(include=["int64", "float64"]).columns:
    df[_c] = df[_c].fillna(df[_c].median())
for _c in df.select_dtypes(include=["object"]).columns:
    df[_c] = df[_c].fillna(df[_c].mode().iloc[0] if not df[_c].mode().empty else "MISSING")

X_train, X_test, y_train, y_test = train_test_split(
    df, target, test_size=0.2, random_state=42, stratify=target
)

numeric_cols = X_train.select_dtypes(include=["int64", "float64"]).columns.tolist()
categorical_cols = X_train.select_dtypes(include=["object"]).columns.tolist()

preprocessor = ColumnTransformer([
    ("num", "passthrough", numeric_cols),
    ("cat", OrdinalEncoder(handle_unknown="use_encoded_value", unknown_value=-1), categorical_cols),
])

if _use_optuna:
    def _objective(trial):
        params = {}
        for _name, _spec in _search_space.items():
            if _spec["type"] == "int":
                params[_name] = trial.suggest_int(_name, _spec["low"], _spec["high"])
            elif _spec["type"] == "float":
                params[_name] = trial.suggest_float(_name, _spec["low"], _spec["high"])
        params["random_state"] = 42
        params["verbose"] = -1
        _model = Pipeline([("preprocessor", preprocessor), ("estimator", lgb.LGBMClassifier(**params))])
        _model.fit(X_train, y_train)
        _y_pred = _model.predict_proba(X_test)[:, 1]
        return roc_auc_score(y_test, _y_pred)

    study = optuna.create_study(direction="maximize")
    study.optimize(_objective, n_trials=10)
    best_params = study.best_params
    best_params["random_state"] = 42
    best_params["verbose"] = -1
else:
    best_params = {"n_estimators": 100, "random_state": 42, "verbose": -1}

estimator = lgb.LGBMClassifier(**best_params)
model = Pipeline([
    ("preprocessor", preprocessor),
    ("estimator", estimator),
])
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
y_proba = model.predict_proba(X_test)[:, 1]
acc = accuracy_score(y_test, y_pred)
auc = roc_auc_score(y_test, y_proba)
print(f"Accuracy: {acc:.4f}")
print(f"AUC: {auc:.4f}")

_outputs_dir = os.getenv("OUTPUTS_DIR", "./outputs")
output_dir = os.path.join(_outputs_dir, "test-job-metric", "checkpoints")
os.makedirs(output_dir, exist_ok=True)
checkpoint_path = os.path.join(output_dir, "best.ckpt")
with open(checkpoint_path, "wb") as f:
    pickle.dump(model, f)
print(f"Model saved to {checkpoint_path}")
np.save(os.path.join(output_dir, "y_test.npy"), y_test)
np.save(os.path.join(output_dir, "y_pred.npy"), y_pred)
np.save(os.path.join(output_dir, "y_prob.npy"), y_proba)