"""
Event type constants. The ONLY place event type strings are defined.
"""

MISSION_BRIEF_READY = "MISSION_BRIEF_READY"
TRAINING_SCRIPT_READY = "TRAINING_SCRIPT_READY"
EPOCH_COMPLETE = "EPOCH_COMPLETE"
TRAINING_COMPLETE = "TRAINING_COMPLETE"
CRASH_EVENT = "CRASH_EVENT"
RESUME_TRAINING = "RESUME_TRAINING"
EVALUATION_STARTED = "EVALUATION_STARTED"
EVALUATION_PASS = "EVALUATION_PASS"
EVALUATION_RETRY = "EVALUATION_RETRY"
EVALUATION_FAILED = "EVALUATION_FAILED"
ESCALATE = "ESCALATE"
JOB_FAILED = "JOB_FAILED"
ENDPOINT_LIVE = "ENDPOINT_LIVE"
DRIFT_ALERT = "DRIFT_ALERT"
ARCHITECTURE_EVALUATED = "ARCHITECTURE_EVALUATED"
AGENT_HEARTBEAT_EVENT = "AGENT_HEARTBEAT"
HUMAN_BASELINE_COMPLETE = "HUMAN_BASELINE_COMPLETE"

PLAN_CREATED = "PLAN_CREATED"
PLAN_COMPLETED = "PLAN_COMPLETED"
PLAN_FAILED = "PLAN_FAILED"

STREAM_SCOUT_OUTPUT = "scout_output"
STREAM_FORGE_OUTPUT = "forge_output"
STREAM_FURNACE_FEED = "furnace_feed"
STREAM_FURNACE_OUTPUT = "furnace_output"
STREAM_FURNACE_CRASH = "furnace_crash"
STREAM_DISSECT_OUTPUT = "dissect_output"
STREAM_ARBITER_OUTPUT = "arbiter_output"
STREAM_HARBOR_OUTPUT = "harbor_output"
STREAM_ORCHESTRATOR_OUT = "orchestrator_output"
STREAM_PLANNER_OUTPUT = "planner_output"
STREAM_AGENT_EVENTS = "agent_events"

ALL_EVENT_STREAMS = [
    STREAM_SCOUT_OUTPUT,
    STREAM_FORGE_OUTPUT,
    STREAM_FURNACE_FEED,
    STREAM_FURNACE_OUTPUT,
    STREAM_FURNACE_CRASH,
    STREAM_DISSECT_OUTPUT,
    STREAM_ARBITER_OUTPUT,
    STREAM_HARBOR_OUTPUT,
    STREAM_ORCHESTRATOR_OUT,
    STREAM_PLANNER_OUTPUT,
    STREAM_AGENT_EVENTS,
]

STREAM_AGENT_THINKING = "agent_thinking"
STREAM_THINKING_DELTA = "thinking_delta"
STREAM_SUBACTION = "subaction_progress"

AGENT_EVENT = "AGENT_EVENT"
THINKING_TOKEN = "THINKING_TOKEN"
THINKING_DELTA = "THINKING_DELTA"
SUBACTION_PROGRESS = "SUBACTION_PROGRESS"

GROUP_FORGE = "forge_consumers"
GROUP_FURNACE = "furnace_consumers"
GROUP_DISSECT = "dissect_consumers"
GROUP_ARBITER = "arbiter_consumers"
GROUP_HARBOR = "harbor_consumers"
GROUP_FRONTEND = "frontend_consumers"
GROUP_ORCHESTRATOR = "orchestrator_consumers"
GROUP_SCOUT = "scout_consumers"
GROUP_COCKPIT = "cockpit_consumers"
