"""Prometheus metrics for the Prometheus Swarm system.

All agents should import and use these metrics. The HTTP server
exposes /metrics on port 9090 for Prometheus scraping.
"""

import logging
import os

from prometheus_client import Counter, Gauge, Histogram, start_http_server

logger = logging.getLogger(__name__)

_METRICS_PORT = int(os.getenv("PROMETHEUS_PORT", "9090"))
_METRICS_STARTED = False

# ─── Agent lifecycle counters ────────────────────────────────────────────
AGENT_RUNS = Counter(
    "swarm_agent_runs_total",
    "Total number of agent run invocations",
    ["agent", "job_id"],
)
AGENT_RUN_DURATION = Histogram(
    "swarm_agent_run_duration_seconds",
    "Duration of agent run invocations",
    ["agent", "job_id"],
    buckets=(0.1, 0.5, 1.0, 2.5, 5.0, 10.0, 30.0, 60.0, 120.0, 300.0, 600.0),
)
AGENT_ERRORS = Counter(
    "swarm_agent_errors_total",
    "Total number of agent errors",
    ["agent", "job_id", "error_type"],
)
AGENT_LLM_CALLS = Counter(
    "swarm_agent_llm_calls_total",
    "Total number of LLM API calls",
    ["agent", "job_id"],
)
AGENT_LLM_TOKENS = Counter(
    "swarm_agent_llm_tokens_total",
    "Total LLM tokens consumed",
    ["agent", "job_id", "direction"],
)
AGENT_LLM_COST = Counter(
    "swarm_agent_llm_cost_usd_total",
    "Total LLM API cost in USD",
    ["agent", "job_id"],
)
AGENT_HEARTBEAT = Gauge(
    "swarm_agent_heartbeat",
    "Unix timestamp of last agent heartbeat",
    ["agent", "job_id"],
)

# ─── Forge-specific metrics ──────────────────────────────────────────────
FORGE_ARCHITECTURE_SELECTIONS = Counter(
    "swarm_forge_architecture_selections_total",
    "Number of architecture selections by type",
    ["architecture", "job_id"],
)
FORGE_SCRIPTS_GENERATED = Counter(
    "swarm_forge_scripts_generated_total",
    "Number of training scripts generated by architecture",
    ["architecture", "job_id"],
)
FORGE_SCRIPTS_GENERATION_DURATION = Histogram(
    "swarm_forge_script_generation_duration_seconds",
    "Duration of script generation",
    ["architecture", "job_id"],
    buckets=(0.1, 0.5, 1.0, 2.0, 5.0, 10.0),
)
FORGE_PLANS_GENERATED = Counter(
    "swarm_forge_plans_generated_total",
    "Number of engineering plans generated",
    ["job_id"],
)
FORGE_TEMPLATES_USED = Counter(
    "swarm_forge_templates_used_total",
    "Number of Jinja template renders (vs f-string fallback)",
    ["architecture", "job_id"],
)
FORGE_PREVENTIONS_APPLIED = Counter(
    "swarm_forge_preventions_applied_total",
    "Number of prevention rules applied to generated scripts",
    ["architecture", "job_id"],
)
FORGE_ERROR_PREVENTIONS_AUTO = Counter(
    "swarm_forge_error_preventions_auto_total",
    "Number of auto-generated prevention rules from error stats",
    ["architecture", "category"],
)
FORGE_STRATEGY_ROUTES = Counter(
    "swarm_forge_strategy_routes_total",
    "Confidence-threshold routing decisions: template / cache / llm",
    ["strategy", "architecture", "job_id"],
)

# ─── Furnace-specific metrics ────────────────────────────────────────────
FURNACE_TRAINING_RUNS = Counter(
    "swarm_furnace_training_runs_total",
    "Total number of training runs (including retries)",
    ["job_id", "mode"],
)
FURNACE_EPOCHS = Counter(
    "swarm_furnace_epochs_total",
    "Total epochs trained",
    ["job_id"],
)
FURNACE_CRASHES = Counter(
    "swarm_furnace_crashes_total",
    "Total training crashes",
    ["job_id", "exception_type"],
)
FURNACE_CRASHES_RECOVERED = Counter(
    "swarm_furnace_crashes_recovered_total",
    "Total crashes successfully recovered by Dissect",
    ["job_id"],
)
FURNACE_BEST_VAL_METRIC = Gauge(
    "swarm_furnace_best_val_metric",
    "Best validation metric achieved",
    ["job_id", "metric_type"],
)

# ─── Dissect-specific metrics ────────────────────────────────────────────
DISSECT_ERROR_CLASSIFICATIONS = Counter(
    "swarm_dissect_classifications_total",
    "Number of error classifications by category",
    ["category", "job_id"],
)
DISSECT_PATCHES_GENERATED = Counter(
    "swarm_dissect_patches_generated_total",
    "Number of patches generated by category",
    ["category", "job_id"],
)
DISSECT_PATCH_DURATION = Histogram(
    "swarm_dissect_patch_duration_seconds",
    "Duration of patch generation",
    ["category", "job_id"],
    buckets=(0.5, 1.0, 2.5, 5.0, 10.0, 30.0, 60.0),
)
DISSECT_CASCADE_LEVEL = Counter(
    "swarm_dissect_cascade_level_total",
    "Repair distribution by cascade level",
    ["level", "job_id"],
)
DISSECT_CASCADE_HITS = Counter(
    "swarm_dissect_cascade_hits_total",
    "Successful matches per cascade level",
    ["level", "category", "job_id"],
)
DISSECT_CASCADE_MISSES = Counter(
    "swarm_dissect_cascade_misses_total",
    "Non-matches per cascade level (rule didn't fire, template didn't match, etc.)",
    ["level", "reason", "job_id"],
)
DISSECT_CASCADE_ERRORS = Counter(
    "swarm_dissect_cascade_errors_total",
    "Unexpected errors thrown by cascade level handlers",
    ["level", "job_id"],
)
DISSECT_LLM_BUDGET_EXHAUSTED = Counter(
    "swarm_dissect_llm_budget_exhausted_total",
    "Times LLM budget was exhausted before repair",
    ["job_id"],
)
DISSECT_OUTCOMES = Counter(
    "swarm_dissect_outcomes_total",
    "Dissect outcome (resume vs escalate)",
    ["outcome", "job_id"],
)

# ─── Harbor-specific metrics ─────────────────────────────────────────────
HARBOR_DEPLOYS = Counter(
    "swarm_harbor_deploys_total",
    "Total deployments",
    ["job_id", "framework", "status"],
)
HARBOR_SERVING_LATENCY = Histogram(
    "swarm_harbor_serving_latency_seconds",
    "Serving request latency",
    ["job_id"],
    buckets=(0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1.0),
)
HARBOR_ACTIVE_DEPLOYMENTS = Gauge(
    "swarm_harbor_active_deployments",
    "Number of currently active deployments",
    ["job_id"],
)

# ─── Scout-specific metrics ──────────────────────────────────────────────
SCOUT_DATASETS_PROCESSED = Counter(
    "swarm_scout_datasets_processed_total",
    "Number of datasets processed",
    ["job_id", "status"],
)
SCOUT_ANALYSIS_DURATION = Histogram(
    "swarm_scout_analysis_duration_seconds",
    "Duration of dataset analysis",
    ["job_id"],
    buckets=(1.0, 2.0, 5.0, 10.0, 30.0, 60.0, 120.0),
)

# ─── Experience Memory metrics ───────────────────────────────────────────
EXPERIENCE_STORED = Counter(
    "swarm_experience_stored_total",
    "Number of experience records stored",
    ["job_id", "outcome"],
)
EXPERIENCE_QUERIED = Counter(
    "swarm_experience_queried_total",
    "Number of experience queries performed",
    ["job_id", "agent"],
)

# ─── Arbiter-specific metrics ────────────────────────────────────────────
ARBITER_DECISIONS = Counter(
    "swarm_arbiter_decisions_total",
    "Number of arbiter decisions by result",
    ["job_id", "decision"],
)
ARBITER_BENCHMARK_EVALUATION_DURATION = Histogram(
    "swarm_arbiter_benchmark_duration_seconds",
    "Duration of benchmark evaluation",
    ["job_id"],
    buckets=(1.0, 5.0, 10.0, 30.0, 60.0, 120.0, 300.0),
)

# ─── Pipeline-level metrics ──────────────────────────────────────────────
PIPELINE_JOBS = Counter(
    "swarm_pipeline_jobs_total",
    "Total pipeline jobs processed",
    ["status"],
)
PIPELINE_JOB_DURATION = Histogram(
    "swarm_pipeline_job_duration_seconds",
    "End-to-end pipeline job duration",
    ["status"],
    buckets=(10.0, 30.0, 60.0, 120.0, 300.0, 600.0, 1800.0, 3600.0),
)
PIPELINE_ACTIVE_JOBS = Gauge(
    "swarm_pipeline_active_jobs",
    "Number of currently active pipeline jobs",
)
PIPELINE_GATE_STATUS = Gauge(
    "swarm_pipeline_gate_status",
    "Status of validation gates (1=pass, 0=fail)",
    ["gate_name"],
)

# ─── Quality Feedback metrics ────────────────────────────────────────────
QUALITY_FEEDBACK_QUERIES = Counter(
    "swarm_quality_feedback_queries_total",
    "Quality feedback query count by operation and outcome",
    ["operation", "success"],
)
QUALITY_FEEDBACK_LATENCY = Histogram(
    "swarm_quality_feedback_latency_seconds",
    "Latency of quality feedback operations",
    ["operation"],
    buckets=(0.001, 0.005, 0.01, 0.025, 0.05, 0.1, 0.5, 1.0),
)
QUALITY_FEEDBACK_RECONNECTS_TOTAL = Counter(
    "swarm_quality_feedback_reconnects_total",
    "Number of times quality feedback reconnected to Redis (stale connection indicator)",
    ["operation"],
)

# ─── Redis stream metrics ────────────────────────────────────────────────
REDIS_STREAM_MESSAGES = Counter(
    "swarm_redis_stream_messages_total",
    "Messages published to Redis streams",
    ["stream", "event_type"],
)
REDIS_STREAM_LAG = Gauge(
    "swarm_redis_stream_lag",
    "Approximate consumer group lag per stream",
    ["stream", "group"],
)
REDIS_STREAM_PENDING = Gauge(
    "swarm_redis_stream_pending",
    "Pending (unacknowledged) messages per consumer group",
    ["stream", "group"],
)


def _check_port(port: int) -> bool:
    import socket

    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        return s.connect_ex(("127.0.0.1", port)) != 0


def start_metrics_server(port: int | None = None) -> None:
    global _METRICS_STARTED
    if _METRICS_STARTED:
        return
    target_port = port or _METRICS_PORT
    if not _check_port(target_port):
        logger.warning(f"Metrics port {target_port} already in use — skipping start")
        _METRICS_STARTED = True
        return
    try:
        start_http_server(target_port)
        _METRICS_STARTED = True
        logger.info(f"Prometheus metrics server started on port {target_port}")
    except Exception as e:
        logger.warning(f"Failed to start Prometheus HTTP server: {e}")


def record_agent_llm(
    agent: str, job_id: str, input_tokens: int, output_tokens: int, cost: float
) -> None:
    AGENT_LLM_CALLS.labels(agent=agent, job_id=job_id).inc()
    AGENT_LLM_TOKENS.labels(agent=agent, job_id=job_id, direction="input").inc(input_tokens)
    AGENT_LLM_TOKENS.labels(agent=agent, job_id=job_id, direction="output").inc(output_tokens)
    AGENT_LLM_COST.labels(agent=agent, job_id=job_id).inc(cost)


def record_agent_error(agent: str, job_id: str, error_type: str) -> None:
    AGENT_ERRORS.labels(agent=agent, job_id=job_id, error_type=error_type).inc()


def record_heartbeat(agent: str, job_id: str) -> None:
    import time

    AGENT_HEARTBEAT.labels(agent=agent, job_id=job_id).set(time.time())


def record_pipeline_job(status: str) -> None:
    PIPELINE_JOBS.labels(status=status).inc()


__all__ = [
    "start_metrics_server",
    "record_agent_llm",
    "record_agent_error",
    "record_heartbeat",
    "record_pipeline_job",
    # Counter references for direct use
    "AGENT_RUNS",
    "AGENT_RUN_DURATION",
    "AGENT_ERRORS",
    "AGENT_LLM_CALLS",
    "AGENT_LLM_TOKENS",
    "AGENT_LLM_COST",
    "AGENT_HEARTBEAT",
    "FORGE_ARCHITECTURE_SELECTIONS",
    "FORGE_SCRIPTS_GENERATED",
    "FORGE_SCRIPTS_GENERATION_DURATION",
    "FORGE_PLANS_GENERATED",
    "FORGE_TEMPLATES_USED",
    "FORGE_PREVENTIONS_APPLIED",
    "FORGE_ERROR_PREVENTIONS_AUTO",
    "FORGE_STRATEGY_ROUTES",
    "FURNACE_TRAINING_RUNS",
    "FURNACE_EPOCHS",
    "FURNACE_CRASHES",
    "FURNACE_CRASHES_RECOVERED",
    "FURNACE_BEST_VAL_METRIC",
    "DISSECT_ERROR_CLASSIFICATIONS",
    "DISSECT_PATCHES_GENERATED",
    "DISSECT_PATCH_DURATION",
    "DISSECT_CASCADE_LEVEL",
    "DISSECT_CASCADE_HITS",
    "DISSECT_CASCADE_MISSES",
    "DISSECT_CASCADE_ERRORS",
    "DISSECT_LLM_BUDGET_EXHAUSTED",
    "DISSECT_OUTCOMES",
    "HARBOR_DEPLOYS",
    "HARBOR_SERVING_LATENCY",
    "HARBOR_ACTIVE_DEPLOYMENTS",
    "SCOUT_DATASETS_PROCESSED",
    "SCOUT_ANALYSIS_DURATION",
    "EXPERIENCE_STORED",
    "EXPERIENCE_QUERIED",
    "ARBITER_DECISIONS",
    "ARBITER_BENCHMARK_EVALUATION_DURATION",
    "PIPELINE_JOBS",
    "PIPELINE_JOB_DURATION",
    "PIPELINE_ACTIVE_JOBS",
    "PIPELINE_GATE_STATUS",
    "REDIS_STREAM_MESSAGES",
    "REDIS_STREAM_LAG",
    "REDIS_STREAM_PENDING",
    "QUALITY_FEEDBACK_QUERIES",
    "QUALITY_FEEDBACK_LATENCY",
    "QUALITY_FEEDBACK_RECONNECTS_TOTAL",
]
