"""
Training script for job 7c11988f-eac8-4023-9d84-a8a10f2a7525
Architecture: lightgbm
Task: binary_classification
Auto-generated by Forge template engine.
Architecture: lightgbm
  Expected training time: ~1 min
  Expected peak memory: ~257 MB
  Expected metric range: [0.75, 0.88]
  Preprocessing: median_imputation_numeric -> mode_imputation_categorical -> ordinal_encoding -> standard_scaling
  Tuning: optuna_bayesian (30 trials)
  Alternatives: xgboost
"""

import os
import json
import pickle
import warnings

import numpy as np
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.metrics import accuracy_score, roc_auc_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OrdinalEncoder
from sklearn.pipeline import Pipeline
import lightgbm as lgb

warnings.filterwarnings("ignore")

import random
random.seed(42)
np.random.seed(42)

_search_space_json = os.getenv("SEARCH_SPACE_JSON")
_use_optuna = bool(_search_space_json and _search_space_json.strip() not in ("", "null", "false", "0"))
if _use_optuna:
    import optuna
    _search_space = json.loads(_search_space_json)

_data_dir = os.getenv("DATA_DIR", "./data")
df = pd.read_csv(os.path.join(_data_dir, "titanic.csv"), sep=",", encoding="utf-8")
target = df.pop("Survived")

mask = target.notna()
df = df[mask]
target = target[mask]

for _c in df.select_dtypes(include="number").columns:
    df[_c] = df[_c].fillna(df[_c].median())
for _c in df.select_dtypes(include=["object"]).columns:
    df[_c] = df[_c].fillna(df[_c].mode().iloc[0] if not df[_c].mode().empty else "MISSING")

_n_classes = target.nunique()
_n_samples = len(target)
if _n_samples < 2:
    print(f"WARNING: Dataset has {_n_samples} rows; using all data for train and test")
    X_train = X_test = df
    y_train = y_test = target
else:
    _use_stratify = _n_classes > 1 and _n_samples >= 4
    X_train, X_test, y_train, y_test = train_test_split(
        df, target, test_size=0.2, random_state=42,
        stratify=target if _use_stratify else None
    )

numeric_cols = X_train.select_dtypes(include="number").columns.tolist()
categorical_cols = X_train.select_dtypes(include=["object"]).columns.tolist()

preprocessor = ColumnTransformer([
    ("num", "passthrough", numeric_cols),
    ("cat", OrdinalEncoder(handle_unknown="use_encoded_value", unknown_value=-1), categorical_cols),
])

if _use_optuna:
    def _objective(trial):
        params = {}
        for _name, _spec in _search_space.items():
            if _spec["type"] == "int":
                params[_name] = trial.suggest_int(_name, _spec["low"], _spec["high"])
            elif _spec["type"] == "float":
                params[_name] = trial.suggest_float(_name, _spec["low"], _spec["high"])
        params["random_state"] = 42
        params["verbose"] = -1
        _model = Pipeline([("preprocessor", preprocessor), ("estimator", lgb.LGBMClassifier(**params))])
        # FAILSAFE: column validation -- verify expected features exist
        _expected_cols = list(dict.fromkeys(_numeric_cols + _cat_cols))
        _missing_cols = [c for c in _expected_cols if c not in X_train.columns]
        if _missing_cols:
            raise ValueError(
                f"FAILSAFE: missing {len(_missing_cols)} expected columns: {_missing_cols} | "
                f"available={list(X_train.columns)[:10]}..."
            )
        
        # FAILSAFE: ensure X_train has rows after NaN filtering
        if len(X_train) == 0:
            raise ValueError("FAILSAFE: X_train has 0 rows -- all data was dropped during NaN filtering")
        

        _model.fit(X_train, y_train)
        _y_pred = _model.predict_proba(X_test)[:, 1]
        return roc_auc_score(y_test, _y_pred)

    study = optuna.create_study(direction="maximize")
    study.optimize(_objective, n_trials=10)
    best_params = study.best_params
    best_params["random_state"] = 42
    best_params["verbose"] = -1
else:
    best_params = {"n_estimators": 100, "random_state": 42, "verbose": -1}

estimator = lgb.LGBMClassifier(**best_params)
model = Pipeline([
    ("preprocessor", preprocessor),
    ("estimator", estimator),
])
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
y_proba = model.predict_proba(X_test)[:, 1]
acc = accuracy_score(y_test, y_pred)
_y_n_classes = y_test.nunique()
if _y_n_classes > 1:
    auc = roc_auc_score(y_test, y_proba)
else:
    auc = float(acc)
print(f"Accuracy: {acc:.4f}")
print(f"AUC: {auc:.4f}")

_outputs_dir = os.getenv("OUTPUTS_DIR", "./outputs")
output_dir = os.path.join(_outputs_dir, "7c11988f-eac8-4023-9d84-a8a10f2a7525", "checkpoints")
os.makedirs(output_dir, exist_ok=True)
checkpoint_path = os.path.join(output_dir, "best.ckpt")
with open(checkpoint_path, "wb") as f:
    pickle.dump(model, f)
print(f"Model saved to {checkpoint_path}")
np.save(os.path.join(output_dir, "y_test.npy"), y_test)
np.save(os.path.join(output_dir, "y_pred.npy"), y_pred)
np.save(os.path.join(output_dir, "y_prob.npy"), y_proba)

result = {"checkpoint_path": checkpoint_path, "val_score": float(auc), "metric": "auc_roc"}
with open(os.path.join(_outputs_dir, "7c11988f-eac8-4023-9d84-a8a10f2a7525", "result.json"), "w") as f:
    json.dump(result, f)
print("TRAINING_COMPLETE")