"""
Training script for job job-c8190be0
Architecture: tabnet
Task: binary
Auto-generated by Forge template engine.
Architecture: lightgbm
  Expected training time: ~1 min
  Expected peak memory: ~263 MB
  Expected metric range: [0.80, 0.92]
  Preprocessing: ordinal_encoding -> standard_scaling
  Tuning: optuna_bayesian (30 trials)
  Alternatives: xgboost
"""

import os
import pickle
import warnings

import numpy as np
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, OrdinalEncoder, StandardScaler
from sklearn.pipeline import Pipeline
from pytorch_tabnet.tab_model import TabNetClassifier, TabNetRegressor

import torch

warnings.filterwarnings("ignore")

import random

random.seed(42)
np.random.seed(42)
torch.manual_seed(42)

_data_dir = os.getenv("DATA_DIR", "./data")
df = pd.read_csv(os.path.join(_data_dir, "churn.csv"), sep=",", encoding="utf-8")
target = df.pop("Churn")

mask = target.notna()
df = df[mask]
target = target[mask]

for _c in df.select_dtypes(include="number").columns:
    df[_c] = df[_c].fillna(df[_c].median())
for _c in df.select_dtypes(include=["object"]).columns:
    df[_c] = df[_c].fillna(df[_c].mode().iloc[0] if not df[_c].mode().empty else "MISSING")

# --- Target encoding: handle string labels like 'Yes'/'No', 'True'/'False' ---
_target_encoder = LabelEncoder()
if target.dtype == object or str(target.dtype) == "category":
    target = pd.Series(_target_encoder.fit_transform(target), index=target.index)
    _target_classes = _target_encoder.classes_.tolist()
else:
    _target_encoder.fit(target)
    _target_classes = _target_encoder.classes_.tolist()

X_train, X_test, y_train, y_test = train_test_split(df, target, test_size=0.2, random_state=42)

numeric_cols = X_train.select_dtypes(include="number").columns.tolist()
categorical_cols = X_train.select_dtypes(include=["object"]).columns.tolist()

for col in categorical_cols:
    _le = LabelEncoder()
    X_train[col] = _le.fit_transform(X_train[col].astype(str))
    X_test[col] = _le.transform(X_test[col].astype(str))

scaler = StandardScaler()
X_train[numeric_cols] = scaler.fit_transform(X_train[numeric_cols])
X_test[numeric_cols] = scaler.transform(X_test[numeric_cols])

X_train = X_train.fillna(0).values.astype(np.float32)
X_test = X_test.fillna(0).values.astype(np.float32)

_device = "cuda" if torch.cuda.is_available() else "cpu"

model = TabNetClassifier(
    n_d=32,
    n_a=32,
    n_steps=5,
    gamma=1.3,
    lambda_sparse=0.001,
    optimizer_fn=torch.optim.Adam,
    optimizer_params=dict(lr=2e-2),
    mask_type="entmax",
    device_name=_device,
)
# FAILSAFE: column validation -- verify expected features exist
_expected_cols = list(dict.fromkeys(numeric_cols + categorical_cols))
_missing_cols = [c for c in _expected_cols if c not in X_train.columns]
if _missing_cols:
    raise ValueError(
        f"FAILSAFE: missing {len(_missing_cols)} expected columns: {_missing_cols} | "
        f"available={list(X_train.columns)[:10]}..."
    )

# FAILSAFE: ensure X_train has rows after NaN filtering
if len(X_train) == 0:
    raise ValueError("FAILSAFE: X_train has 0 rows -- all data was dropped during NaN filtering")


model.fit(
    X_train,
    y_train.values,
    eval_set=[(X_test, y_test.values)],
    eval_metric=["auc"],
    max_epochs=50,
    patience=10,
    batch_size=1024,
    virtual_batch_size=256,
    num_workers=0,
)
y_pred = model.predict(X_test)
y_prob = model.predict_proba(X_test)
acc = (y_pred == y_test.values).mean()
print(f"Accuracy: {float(acc):.4f}")

_outputs_dir = os.getenv("OUTPUTS_DIR", "./outputs")
output_dir = os.path.join(_outputs_dir, "checkpoints")
os.makedirs(output_dir, exist_ok=True)
checkpoint_path = os.path.join(output_dir, "best.ckpt")
_checkpoint = {
    "model": model,
    "target_encoder": _target_encoder,
    "target_classes": _target_classes,
}
with open(checkpoint_path, "wb") as f:
    pickle.dump(_checkpoint, f)
print(f"Model saved to {checkpoint_path}")
np.save(
    os.path.join(output_dir, "y_test.npy"), y_test.values if hasattr(y_test, "values") else y_test
)
np.save(os.path.join(output_dir, "y_pred.npy"), y_pred)
if y_prob.shape[1] == 2:
    y_prob = y_prob[:, 1]
np.save(os.path.join(output_dir, "y_prob.npy"), y_prob)

result = {"checkpoint_path": checkpoint_path, "val_score": float(acc), "metric": "accuracy"}
with open(os.path.join(_outputs_dir, "result.json"), "w") as f:
    json.dump(result, f)
print("TRAINING_COMPLETE")
