"""
Training script for job titanic-e2e
Architecture: lightgbm
Task: classification
Auto-generated by Forge agent.
"""

import os
import pickle
import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, OrdinalEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline


# --- Data loading ---
df = pd.read_csv(r"C:\Users\moham\OneDrive\Desktop\prometheus-swarm\data\titanic.csv")
target = df.pop("Survived")

# Drop high-cardinality text columns (Name, Ticket, Cabin)
for col in ["Name", "Ticket", "Cabin"]:
    if col in df.columns:
        df.drop(columns=[col], inplace=True)

X_train, X_test, y_train, y_test = train_test_split(
    df, target, test_size=0.2, random_state=42
)

# --- Preprocessing ---
numeric_cols = X_train.select_dtypes(include=["int64", "float64"]).columns.tolist()
categorical_cols = X_train.select_dtypes(include=["object"]).columns.tolist()

import lightgbm as lgb

# Build a pipeline with preprocessing + estimator
preprocessor = ColumnTransformer([
    ("num", "passthrough", numeric_cols),
    ("cat", OrdinalEncoder(handle_unknown="use_encoded_value", unknown_value=-1), categorical_cols),
])

if True:
    estimator = lgb.LGBMClassifier(n_estimators=100, random_state=42, verbose=-1)
else:
    estimator = lgb.LGBMRegressor(n_estimators=100, random_state=42, verbose=-1)

model = Pipeline([
    ("preprocessor", preprocessor),
    ("estimator", estimator),
])
model.fit(X_train, y_train)

# --- Evaluation ---
y_pred = model.predict(X_test)
from sklearn.metrics import roc_auc_score, f1_score, accuracy_score
print(f"Accuracy: {accuracy_score(y_test, y_pred):.4f}")

# --- Save checkpoint ---
output_dir = r"outputs/titanic-e2e/checkpoints"
os.makedirs(output_dir, exist_ok=True)
checkpoint_path = os.path.join(output_dir, "best.ckpt")
with open(checkpoint_path, "wb") as f:
    pickle.dump(model, f)
print(f"Model saved to {checkpoint_path}")
