{
  "fixed_script_path": "C:\\Users\\moham\\OneDrive\\Desktop\\prometheus-swarm\\scripts\\training_script_abl-tc08-9d9dec.py",
  "patch_id": "patch-abl-tc08-9d9dec-001",
  "confidence_score": 0.91,
  "error_category": "missing_column"
}
"""
Training script for job abl-tc08-9d9dec
Architecture: lightgbm
Task: classification
Auto-generated by Forge agent.
Imbalance strategy: none
Validation strategy: train_val_split
Design Summary:
  Architecture: lightgbm
    Expected training time: ~1 min
    Expected peak memory: ~260 MB
    Expected metric range: [0.75, 0.88]
    Preprocessing: ordinal_encoding -> standard_scaling
    Tuning: optuna_bayesian (30 trials)
    Alternatives: xgboost
"""

import os
import json
import pickle
import warnings

import numpy as np
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.metrics import accuracy_score, mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OrdinalEncoder
from sklearn.pipeline import Pipeline
import lightgbm as lgb

warnings.filterwarnings("ignore")

_search_space_json = os.getenv("SEARCH_SPACE_JSON")
_use_optuna = bool(_search_space_json)
if _use_optuna:
    import optuna
    _search_space = json.loads(_search_space_json)

_data_dir = os.getenv("DATA_DIR", "./data")
df = pd.read_csv(os.path.join(_data_dir, "tc08_loan_prediction.csv"))

# --- missing_column fix: locate target column case-insensitively ---
_target_col_name = "loan_status"
_col_lower_map = {c.lower().strip(): c for c in df.columns}
if _target_col_name not in df.columns:
    if _target_col_name.lower() in _col_lower_map:
        _target_col_name = _col_lower_map[_target_col_name.lower()]
    else:
        # Try common alternatives
        _candidates = [c for c in df.columns if "loan" in c.lower() and "status" in c.lower()]
        if _candidates:
            _target_col_name = _candidates[0]
        else:
            raise KeyError(
                f"Target column 'loan_status' not found in CSV. "
                f"Available columns: {list(df.columns)}"
            )

target = df.pop(_target_col_name)
# --- end missing_column fix ---

mask = target.notna()
df = df[mask]
target = target[mask]

for _c in df.select_dtypes(include=["int64", "float64"]).columns:
    df[_c] = df[_c].fillna(df[_c].median())
for _c in df.select_dtypes(include=["object"]).columns:
    df[_c] = df[_c].fillna(df[_c].mode().iloc[0] if not df[_c].mode().empty else "MISSING")

X_train, X_test, y_train, y_test = train_test_split(df, target, test_size=0.2, random_state=42)

numeric_cols = X_train.select_dtypes(include=["int64", "float64"]).columns.tolist()
categorical_cols = X_train.select_dtypes(include=["object"]).columns.tolist()

preprocessor = ColumnTransformer([
    ("num", "passthrough", numeric_cols),
    ("cat", OrdinalEncoder(handle_unknown="use_encoded_value", unknown_value=-1), categorical_cols),
])

if _use_optuna:
    if True:
        def _objective(trial):
            params = {}
            for _name, _spec in _search_space.items():
                if _spec["type"] == "int":
                    params[_name] = trial.suggest_int(_name, _spec["low"], _spec["high"])
                elif _spec["type"] == "float":
                    params[_name] = trial.suggest_float(_name, _spec["low"], _spec["high"])
            params["random_state"] = 42
            params["verbosity"] = -1
            _model = Pipeline([("preprocessor", preprocessor), ("estimator", lgb.LGBMClassifier(**params))])
            _model.fit(X_train, y_train)
            _y_pred = _model.predict(X_test)
            return accuracy_score(y_test, _y_pred)
    else:
        def _objective(trial):
            params = {}
            for _name, _spec in _search_space.items():
                if _spec["type"] == "int":
                    params[_name] = trial.suggest_int(_name, _spec["low"], _spec["high"])
                elif _spec["type"] == "float":
                    params[_name] = trial.suggest_float(_name, _spec["low"], _spec["high"])
            params["random_state"] = 42
            params["verbosity"] = -1
            _model = Pipeline([("preprocessor", preprocessor), ("estimator", lgb.LGBMRegressor(**params))])
            _model.fit(X_train, y_train)
            _y_pred = _model.predict(X_test)
            return float(mean_squared_error(y_test, _y_pred))

    _n_trials = 30
    study = optuna.create_study(direction="maximize")
    study.optimize(_objective, n_trials=_n_trials)
    best_params = study.best_params
    best_params["random_state"] = 42
    best_params["verbose"] = -1
else:
    best_params = {"n_estimators": 100, "random_state": 42, "verbose": -1}

if not False:
    if True:
        estimator = lgb.LGBMClassifier(**best_params)
    else:
        estimator = lgb.LGBMRegressor(**best_params)
    model = Pipeline([
        ("preprocessor", preprocessor),
        ("estimator", estimator),
    ])
    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)
    y_pred_class = y_pred
print(f"Accuracy: {accuracy_score(y_test, y_pred_class):.4f}")

_outputs_dir = os.getenv("OUTPUTS_DIR", "./outputs")
output_dir = os.path.join(_outputs_dir, "abl-tc08-9d9dec", "checkpoints")
os.makedirs(output_dir, exist_ok=True)
checkpoint_path = os.path.join(output_dir, "best.ckpt")
with open(checkpoint_path, "wb") as f:
    pickle.dump(model, f)
print(f"Model saved to {checkpoint_path}")
np.save(os.path.join(output_dir, "y_test.npy"), y_test)
np.save(os.path.join(output_dir, "y_pred.npy"), y_pred)
if True:
    y_prob_full = model.predict_proba(X_test)
    if y_prob_full.shape[1] == 2:
        y_prob_full = y_prob_full[:, 1]
    np.save(os.path.join(output_dir, "y_prob.npy"), y_prob_full)